#Application URL
url = https://www.saucedemo.com/

#Browser Configuration
browser = chrome

#Credientials
username = standard_user
password = secret_sauce

#implicit wait (in Seconds)
implicitWait = 20

#Explicit Wait
explicitWait =30